### ISSUE TITLE
error: ReferenceError: localStorage is not defined

### ISSUE THREAD

**Issue by tomyedlp** [Authress/nextjs-starter-kit#1]
There's a bug with localStorage.

Solution might be using a typeof window !== "undefined" before using localStorage.

`{
  title: 'LocalStorage failed in Browser',
  error: ReferenceError: localStorage is not defined
      at LoginClient.userSessionContinuation (webpack-internal:///(ssr)/./node_modules/@authress/login/src/index.js:287:38)
      at LoginClient.userSessionExists (webpack-internal:///(ssr)/./node_modules/@authress/login/src/index.js:280:50)
      at eval (webpack-internal:///(ssr)/./src/app/authressClient.tsx:25:17)
      at (ssr)/./src/app/authressClient.tsx (/workspaces/web-user-login/.next/server/app/unauthorized/page.js:162:1)
      at __webpack_require__ (/workspaces/web-user-login/.next/server/webpack-runtime.js:33:42)
      at eval (webpack-internal:///(ssr)/./src/app/unauthorized/page.tsx:9:73)
      at (ssr)/./src/app/unauthorized/page.tsx (/workspaces/web-user-login/.next/server/app/unauthorized/page.js:173:1)
      at __webpack_require__ (/workspaces/web-user-login/.next/server/webpack-runtime.js:33:42)
      at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:103108
      at eo (/workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:103293)
      at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:105726
      at Object._fromJSON (/workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:106078)
      at JSON.parse (<anonymous>)
      at eu (/workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:103787)
      at en (/workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:102855)
      at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:109661
      at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:109678
      at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:109711
      at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:109728
      at t (/workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:109951)
}`

`ReferenceError: document is not defined
    at UserIdentityTokenStorageManager.getUserCookie (webpack-internal:///(ssr)/./node_modules/@authress/login/src/userIdentityTokenStorageManager.js:7:21)
    at LoginClient.getUserIdentity (webpack-internal:///(ssr)/./node_modules/@authress/login/src/index.js:73:57)
    at LoginClient.userSessionContinuation (webpack-internal:///(ssr)/./node_modules/@authress/login/src/index.js:369:31)
    at LoginClient.userSessionExists (webpack-internal:///(ssr)/./node_modules/@authress/login/src/index.js:280:50)
    at eval (webpack-internal:///(ssr)/./src/app/authressClient.tsx:25:17)
    at (ssr)/./src/app/authressClient.tsx (/workspaces/web-user-login/.next/server/app/unauthorized/page.js:162:1)
    at __webpack_require__ (/workspaces/web-user-login/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(ssr)/./src/app/unauthorized/page.tsx:9:73)
    at (ssr)/./src/app/unauthorized/page.tsx (/workspaces/web-user-login/.next/server/app/unauthorized/page.js:173:1)
    at __webpack_require__ (/workspaces/web-user-login/.next/server/webpack-runtime.js:33:42)
    at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:103108
    at eo (/workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:103293)
    at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:105726
    at Object._fromJSON (/workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:106078)
    at JSON.parse (<anonymous>)
    at eu (/workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:103787)
    at en (/workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:102855)
    at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:109661
    at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:109678
    at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:109711
    at /workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:109728
    at t (/workspaces/web-user-login/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:109951)`

**Comment by wparad** [comment]
Good call. We really appreciate you putting up this issue.

Actually I think there are a couple of things that are happening here, so I'm going to get a PR up to fix these things. As you might have notice, this starter kit was literally just put up. So if you notice any additional oddities or if there are functions missing that would significantly help or reduce friction on development, please let us know!

**Comment by tomyedlp** [comment]
Thank you, I appreciate your response. I will do if I find any issue!
